### ISSUE TITLE
TypeError: Cannot read property 'toString' of undefined

### ISSUE THREAD

**Issue by Wiigian** [terafin/mqtt-netatmo-bridge#38]
When launching docker image, netatmo data is received, but there seems to be an issues with the module homeautomation-js-lib/mqtt ? 

mqtt-netatmo-bridge_1  | [2021-07-05T13:08:51.306] [INFO] mqtt-netatmo-bridge - Looking at module: undefined
mqtt-netatmo-bridge_1  | [2021-07-05T13:08:51.306] [INFO] mqtt-netatmo-bridge -    data: {"time_utc":1625490033,"Temperature":23.5,"CO2":550,"Humidity":45,"Noise":35,"Pressure":1005.3,"AbsolutePressure":935.8,"min_temp":23.3,"max_temp":24.1,"date_max_temp":1625436214,"date_min_temp":1625467041,"temp_trend":"stable","pressure_trend":"stable"}
mqtt-netatmo-bridge_1  | [2021-07-05T13:08:51.306] [INFO] mqtt-netatmo-bridge - starting smart publish
mqtt-netatmo-bridge_1  | /usr/node_app/node_modules/homeautomation-js-lib/mqtt_helpers.js:149
mqtt-netatmo-bridge_1  |         const component = arguments[i].toString()
mqtt-netatmo-bridge_1  |                                        ^
mqtt-netatmo-bridge_1  | 
mqtt-netatmo-bridge_1  | TypeError: Cannot read property 'toString' of undefined
mqtt-netatmo-bridge_1  |     at Object.exports.generateTopic (/usr/node_app/node_modules/homeautomation-js-lib/mqtt_helpers.js:149:40)
mqtt-netatmo-bridge_1  |     at processModule (/usr/node_app/mqtt-netatmo-bridge.js:219:48)
mqtt-netatmo-bridge_1  |     at netatmo.getStationsData (/usr/node_app/mqtt-netatmo-bridge.js:114:5)
mqtt-netatmo-bridge_1  |     at netatmo.emit (events.js:375:28)
mqtt-netatmo-bridge_1  |     at netatmo.<anonymous> (/usr/node_app/node_modules/netatmo/netatmo.js:224:10)
mqtt-netatmo-bridge_1  |     at Request.self.callback (/usr/node_app/node_modules/request/request.js:185:22)
mqtt-netatmo-bridge_1  |     at Request.emit (events.js:375:28)
mqtt-netatmo-bridge_1  |     at Request.<anonymous> (/usr/node_app/node_modules/request/request.js:1154:10)
mqtt-netatmo-bridge_1  |     at Request.emit (events.js:375:28)
mqtt-netatmo-bridge_1  |     at IncomingMessage.<anonymous> (/usr/node_app/node_modules/request/request.js:1076:12)
mqtt-netatmo-bridge_1  | npm ERR! code ELIFECYCLE
mqtt-netatmo-bridge_1  | npm ERR! errno 1
mqtt-netatmo-bridge_1  | npm ERR! mqtt-netatmo-bridge@0.0.1 start: `node mqtt-netatmo-bridge.js`
mqtt-netatmo-bridge_1  | npm ERR! Exit status 1
mqtt-netatmo-bridge_1  | npm ERR! 
mqtt-netatmo-bridge_1  | npm ERR! Failed at the mqtt-netatmo-bridge@0.0.1 start script.
mqtt-netatmo-bridge_1  | npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
mqtt-netatmo-bridge_1  | 
mqtt-netatmo-bridge_1  | npm ERR! A complete log of this run can be found in:
mqtt-netatmo-bridge_1  | npm ERR!     /root/.npm/_logs/2021-07-05T13_08_51_361Z-debug.log
docker_mqtt-netatmo-bridge_1 exited with code 1

**Comment by Wiigian** [comment]
Closing issue, this was related to a missing module name, causing the "undefined". 
Adding a name to the module using the Netatmo app fixed the problem.
